def isGerritReview = false

pipeline {
  agent {
    label 'maratona'
  }
  stages {
    stage('Build') {
      steps {
        script {
          isGerritReview = (env.GERRIT_CHANGE_NUMBER || env.CHANGE_ID)
          sh 'mkdir -p $HOME/.m2 $HOME/.npm'

          docker.withRegistry('', '') {
            docker.image('maven:3.9.9-eclipse-temurin-21').inside('-v $HOME/.m2:/var/maven/.m2 -v $HOME/.npm:/.npm') {

              if (isGerritReview) {
                echo "Building Gerrit Change Review..."
              } else {
                echo "Building Main Branch Post-Merge..."
              }

              sh 'mvn -Dmaven.repo.local=/var/maven/.m2/repository -U clean package'
            }
          }
        }
      }
    }
    stage('Static Analysis') {
      steps {
        script {
          docker.withRegistry('', '') {
            docker.image('maven:3.9.9-eclipse-temurin-21').inside('-v $HOME/.m2:/var/maven/.m2 -v $HOME/.npm:/.npm') {
              sh '''
                mvn -Dmaven.repo.local=/var/maven/.m2/repository verify \
                -Dcheckstyle.failOnViolation=false \
                -Dpmd.failOnViolation=false \
                -Dcpd.failOnViolation=false \
                -Dspotbugs.failOnError=false
              '''
            }
          }
        }
      }
      post {
        always {
          script {
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'

            recordCoverage(tools: [[parser: 'JACOCO', pattern: '**/target/site/jacoco/jacoco.xml']],
                    id: 'jacoco', name: 'JaCoCo Coverage')

            recordIssues(
              enabledForFailure: true,
              aggregatingResults: false,
              tools: [
                checkStyle(pattern: '**/target/checkstyle-result.xml'),
                pmdParser(pattern: '**/target/pmd.xml'),
                cpd(pattern: '**/target/cpd.xml'),
                spotBugs(pattern: '**/target/spotbugsXml.xml')
              ],
              qualityGates: []
            )
          }
        }
      }
    }
  }
  post {
    success {
      script {
        if (isGerritReview) {
          gerritReview labels: [Verified: 1], notify: 'NONE'
        } else {
          echo "Main branch build successful. Skipping Gerrit vote."
        }
      }
    }
    unstable {
      script {
        if (isGerritReview) {
          gerritReview labels: [Verified: 0], message: 'Build is unstable'
        }
      }
    }
    failure {
      script {
        if (isGerritReview) {
          gerritReview labels: [Verified: -1]
        }
      }
    }
  }
}
