// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.googlesource.gerrit.plugins.aicodereview.settings;

import java.util.Map;

public class Settings {
  public static final String GERRIT_PATCH_SET_FILENAME = "/PATCHSET_LEVEL";
  public static final String GERRIT_DEFAULT_MESSAGE_DONE = "Done";
  public static final String GERRIT_AUTOGENERATED_PREFIX = "autogenerated:";
  public static final Map<String, String> COMMIT_MESSAGE_FILTER_OUT_PREFIXES =
      Map.of(
          "PARENT", "Parent:",
          "AUTHOR", "Author:",
          "AUTHOR_DATE", "AuthorDate:",
          "COMMIT", "Commit:",
          "COMMIT_DATE", "CommitDate:",
          "CHANGE_ID", "Change-Id:");
  public static final String GERRIT_COMMIT_MESSAGE_PREFIX = "Subject: ";

  public static final String OPEN_AI_CHAT_ROLE_USER = "user";
  public static final String OPEN_AI_CHAT_ROLE_ASSISTANT = "assistant";

  public enum Modes {
    stateless,
    stateful
  }

  public enum AIType {
    CHATGPT,
    OLLAMA,
    AZUREOPENAI,

    // Azure AI Foundry Agent. Unlike AZUREOPENAI (which calls the Chat Completions API with a model
    // deployment), this type invokes a named Foundry Agent through the Responses API
    // (/conversations + /responses with an agent_reference).
    AZUREAGENT,

    // used for testing new endpoints and ai services not yet in the supported list, but you can
    // specify the
    // endpoint, the authorization header information, and the prompt to quickly prove out a new
    // aiType.
    GENERIC;
  }
}
