/*
 * Copyright (c) 2026. The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.googlesource.gerrit.plugins.reviewai.web;

import com.google.gerrit.extensions.common.AccountInfo;
import com.google.gerrit.extensions.common.ChangeMessageInfo;
import com.google.gerrit.extensions.common.CommentInfo;
import com.googlesource.gerrit.plugins.reviewai.aibackend.common.model.api.gerrit.GerritComment;
import com.googlesource.gerrit.plugins.reviewai.settings.Settings;
import org.junit.Test;

import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class AiReviewHistoryTest {
  @Test
  public void mergeCommentsAddsPatchSetMessagesToInlineComments() {
    CommentInfo inlineComment = new CommentInfo();
    inlineComment.id = "c-1";
    inlineComment.message = "@reviewai please inspect this block";
    inlineComment.patchSet = 4;
    inlineComment.author = account(1001, "Alice");

    ChangeMessageInfo userPatchSetMessage = new ChangeMessageInfo();
    userPatchSetMessage.id = "msg-1";
    userPatchSetMessage.message = "Patch Set 4:\n\n@reviewai please review this change";
    userPatchSetMessage._revisionNumber = 4;
    userPatchSetMessage.date = Timestamp.valueOf("2026-04-10 09:00:00");
    userPatchSetMessage.author = account(1002, "Bob");

    ChangeMessageInfo aiPatchSetMessage = new ChangeMessageInfo();
    aiPatchSetMessage.id = "msg-2";
    aiPatchSetMessage.message = "This is the AI review output.";
    aiPatchSetMessage._revisionNumber = 4;
    aiPatchSetMessage.date = Timestamp.valueOf("2026-04-10 09:01:00");
    aiPatchSetMessage.tag = "autogenerated:reviewai";
    aiPatchSetMessage.author = account(7, "ReviewAI");

    Map<String, List<GerritComment>> mergedComments =
        AiReviewHistory.mergeComments(
            Map.of("src/main/java/Foo.java", List.of(inlineComment)),
            List.of(userPatchSetMessage, aiPatchSetMessage));

    assertEquals(2, mergedComments.size());
    assertEquals(1, mergedComments.get("src/main/java/Foo.java").size());
    assertEquals(2, mergedComments.get(Settings.GERRIT_PATCH_SET_FILENAME).size());
    assertTrue(
        mergedComments.get(Settings.GERRIT_PATCH_SET_FILENAME).stream()
            .anyMatch(comment -> "msg-1".equals(comment.getId())));
    assertTrue(
        mergedComments.get(Settings.GERRIT_PATCH_SET_FILENAME).stream()
            .anyMatch(comment -> "msg-2".equals(comment.getId())));
  }

  @Test
  public void mergeCommentsCarriesReviewScoreFromDuplicateChangeMessage() {
    CommentInfo patchSetComment = new CommentInfo();
    patchSetComment.id = "patchset-comment-1";
    patchSetComment.changeMessageId = "msg-1";
    patchSetComment.message = "This is the AI review output.";
    patchSetComment.patchSet = 4;
    patchSetComment.author = account(7, "ReviewAI");

    ChangeMessageInfo scoredMessage = new ChangeMessageInfo();
    scoredMessage.id = "msg-1";
    scoredMessage.message = "Patch Set 4: Code-Review-1\n\n(1 comment)";
    scoredMessage._revisionNumber = 4;
    scoredMessage.date = Timestamp.valueOf("2026-04-10 09:01:00");
    scoredMessage.tag = "autogenerated:reviewai";
    scoredMessage.author = account(7, "ReviewAI");

    Map<String, List<GerritComment>> mergedComments =
        AiReviewHistory.mergeComments(
            Map.of(Settings.GERRIT_PATCH_SET_FILENAME, List.of(patchSetComment)),
            List.of(scoredMessage));

    List<GerritComment> patchSetComments = mergedComments.get(Settings.GERRIT_PATCH_SET_FILENAME);
    assertEquals(1, patchSetComments.size());
    assertEquals("This is the AI review output.", patchSetComments.get(0).getMessage());
    assertEquals("-1", patchSetComments.get(0).getReviewScore());
  }

  private static AccountInfo account(int accountId, String name) {
    AccountInfo account = new AccountInfo(accountId);
    account.name = name;
    account.username = name.toLowerCase();
    return account;
  }
}
